<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
  "-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
  "http://tapestry.apache.org/dtd/Script_3_0.dtd">

<script>

<input-symbol key="component" required="yes" />

<initialization>
	<unique>
		function check(){ 
		if (dojo.byId("${component.eventHeaderId}").checked)
			return true;
		else
			return false;
		}
	</unique>
</initialization>
</script>