<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
  "-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
  "http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>
<input-symbol key="id" required="yes" />
<initialization>
dojo.event.connect(dojo.byId("${id}"),"onclick",function(evt){
	var src=dojo.html.getEventTarget(evt);
	queryBox.onSelect(src);
	queryBox.win.close();
}); 
</initialization>
</script>