<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  copyright:	Beijing Maxinfo Technology Ltd. http://www.bjmaxinfo.com
-->

<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
  
<script>
<include-script resource-path="/corner/corner.js"/>
<include-script resource-path="/corner/sc-17-proto-15-compressed.js"/>
</script>

