<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>

<input-symbol key="json" required="yes" />
<input-symbol key="json2" required="yes" />
<input-symbol key="type" required="yes" />

<initialization>
	var flags = eval(${json});
	var flags2 = eval(${json2});
	var type = "${type}";
</initialization>
</script>