<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>

<input-symbol key="link1" required="yes" />
<input-symbol key="link2" required="yes" />

<initialization>
	$("ver_download").href = "${link1}";
	$("otherVer_download").href = "${link2}";
</initialization>
</script>